# Titanic Spaceship - Kaggle competition 

I'm trying to solve this kagle competition using ML algorithms and some data techinics. This notes are divided in three parts: 
* 1 - Data analysis and visualization 
* 2 - Try to predict who's survive in the spaceship accident 
* 3 - Conclusions 

In [ ]:
# importing libraries 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly as pl  
import plotly.express as px
import numpy as np

In [ ]:
df_test = pd.read_csv('test.csv')
df_train = pd.read_csv('train.csv')

79.0

In [ ]:
df_train

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines   
...           ...        ...           ...     ...     ...                ...   
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
0           False  
1            True  
2           False  
3           False  
4            True  
...           ...  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True  

[8693 rows x 14 columns]

In [ ]:
df_test

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0013_01      Earth      True     G/3/S    TRAPPIST-1e  27.0  False   
1        0018_01      Earth     False     F/4/S    TRAPPIST-1e  19.0  False   
2        0019_01     Europa      True     C/0/S    55 Cancri e  31.0  False   
3        0021_01     Europa     False     C/1/S    TRAPPIST-1e  38.0  False   
4        0023_01      Earth     False     F/5/S    TRAPPIST-1e  20.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
4272     9266_02      Earth      True  G/1496/S    TRAPPIST-1e  34.0  False   
4273     9269_01      Earth     False       NaN    TRAPPIST-1e  42.0  False   
4274     9271_01       Mars      True   D/296/P    55 Cancri e   NaN  False   
4275     9273_01     Europa     False   D/297/P            NaN   NaN  False   
4276     9277_01      Earth      True  G/1498/S  PSO J318.5-22  43.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0             0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1             0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2             0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3             0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4            10.0        0.0         635.0     0.0     0.0   Brence Harperez  
...           ...        ...           ...     ...     ...               ...  
4272          0.0        0.0           0.0     0.0     0.0       Jeron Peter  
4273          0.0      847.0          17.0    10.0   144.0     Matty Scheron  
4274          0.0        0.0           0.0     0.0     0.0       Jayrin Pore  
4275          0.0     2680.0           0.0     0.0   523.0    Kitakan Conale  
4276          0.0        0.0           0.0     0.0     0.0  Lilace Leonzaley  

[4277 rows x 13 columns]

## Clean the data 

Some Columns clearly doesn't influences on data, by instance : Passenger Id and Name. So I'm going to drop these columns

In [ ]:
del df_train['PassengerId']
del df_train['Name']
df_train.drop('Cabin',axis=1,inplace=True)

In [ ]:
del df_test['PassengerId']
del df_test['Name']
df_test.drop('Cabin',axis=1,inplace=True)

In this point I realized there's a lot missing values in the data, as a first approximation I'm justing droping these rows with missing values. Doing this I lost approximately 2000 rows, and it'll not work so fine as I want 

In [ ]:
df_train.isnull().sum()

HomePlanet      201
CryoSleep       217
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Transported       0
dtype: int64

In [ ]:
df_train.dropna(inplace=True)

Now, we're going to handle with the outliers : The criterion follows: every data that's bigger than 2.0*(the mean of third quarter) is going to be dropped in the numerical data
* After some critical thinking I realized that the outliers may be important in this case, so I'll keep them.

In [ ]:
#print( 'third quarter Room Service = ' , df_train['RoomService'].quantile(0.75))
#df_train = df_train[df_train['RoomService']< 47*20]

In [ ]:
#print( 'third quarter ShoppingMall = ' , df_train['ShoppingMall'].quantile(0.75))
#df_train = df_train[df_train['ShoppingMall'] < 27*20]

In [ ]:
#print( 'third quarter Spa = ' , df_train['Spa'].quantile(0.75))
#df_train = df_train[df_train['Spa'] < 59*20]

In [ ]:
#print( 'third quarter VRDeck = ' , df_train['VRDeck'].quantile(0.75))
#df_train = df_train[df_train['VRDeck'] < 46*20]

In [ ]:
#print( 'third quarter FoodCourt = ' , df_train['FoodCourt'].quantile(0.75))
#df_train = df_train[df_train['FoodCourt'] < 46*20]

## visualizating the Data

All right, of course we're going to work in the train data. By now, the idea is to clean the data and to apply some ML in the train data in order to predict wheter someone is surviving or not. Let's take a better look into the data, first I'm looking to the matrix graphs of numericals variables.

In [ ]:
grafico = px.scatter_matrix(df_train, dimensions=['Age','RoomService','FoodCourt','ShoppingMall','Spa'], color = 'Transported')
grafico.show()

In [ ]:
fig = px.histogram(df_train, x="Age",color='Transported')
fig.show()

In [ ]:
fig = px.histogram(df_train[df_train['RoomService'] > 10], x="RoomService",color='Transported')
fig.show()

In [ ]:
fig = px.histogram(df_train, x="Spa",color='Transported')
fig.show()

Some observations at first glance:
* 1- People with lower  Roomservice has a bigger probability of being transported. 
* 2- People with a lower Spa has a bigger probability of being transported. 

Let's take a look to some histograms of the system.

In [ ]:
np.unique(df_train['Transported'], return_counts=True)

(array([False,  True]), array([3440, 3483]))

Again, demostrating the tendency that people who spend more is not transported. As I suspected, the age doesn't seems to care, So I'm dropping that too.

In [ ]:
df_train.drop('Age',axis=1,inplace=True)
df_test.drop('Age',axis=1,inplace=True)


## The strings in data

In [ ]:
df_train.groupby(['HomePlanet']).count()

CryoSleep  Destination   VIP  RoomService  FoodCourt  \
HomePlanet                                                         
Earth            3736         3736  3736         3736       3736   
Europa           1763         1763  1763         1763       1763   
Mars             1424         1424  1424         1424       1424   

            ShoppingMall   Spa  VRDeck  Transported  
HomePlanet                                           
Earth               3736  3736    3736         3736  
Europa              1763  1763    1763         1763  
Mars                1424  1424    1424         1424

In [ ]:
grafico = px.parallel_categories(df_train,dimensions=['HomePlanet','Transported'])
grafico.show()

In [ ]:
df_train.groupby(['VIP']).count()

HomePlanet  CryoSleep  Destination  RoomService  FoodCourt  \
VIP                                                                 
False        6754       6754         6754         6754       6754   
True          169        169          169          169        169   

       ShoppingMall   Spa  VRDeck  Transported  
VIP                                             
False          6754  6754    6754         6754  
True            169   169     169          169

In [ ]:
grafico = px.parallel_categories(df_train,dimensions=['VIP','Transported'])
grafico.show()

In [ ]:
df_train.groupby(['CryoSleep']).count()

HomePlanet  Destination   VIP  RoomService  FoodCourt  \
CryoSleep                                                          
False            4474         4474  4474         4474       4474   
True             2449         2449  2449         2449       2449   

           ShoppingMall   Spa  VRDeck  Transported  
CryoSleep                                           
False              4474  4474    4474         4474  
True               2449  2449    2449         2449

In [ ]:
grafico = px.parallel_categories(df_train,dimensions=['CryoSleep','Transported'])
grafico.show()

In [ ]:
df_train.groupby(['Destination']).count()

HomePlanet  CryoSleep   VIP  RoomService  FoodCourt  \
Destination                                                          
55 Cancri e          1482       1482  1482         1482       1482   
PSO J318.5-22         655        655   655          655        655   
TRAPPIST-1e          4786       4786  4786         4786       4786   

               ShoppingMall   Spa  VRDeck  Transported  
Destination                                             
55 Cancri e            1482  1482    1482         1482  
PSO J318.5-22           655   655     655          655  
TRAPPIST-1e            4786  4786    4786         4786

In [ ]:
grafico = px.parallel_categories(df_train,dimensions=['Destination','Transported'])
grafico.show()

By this moment, we can conclude that we have a lot more False VIP's so I'm going to drop this column. Beside that, the destination doesn't care too much, so I'll drop that too

In [ ]:
df_train.drop('Destination',axis=1,inplace=True,)

In [ ]:
df_train.drop('VIP',axis=1,inplace=True,)

In [ ]:
df_train.drop('HomePlanet',axis=1,inplace=True,)

In [ ]:
df.isnull().sum()

CryoSleep       93
RoomService      0
FoodCourt        0
ShoppingMall     0
Spa              0
VRDeck           0
dtype: int64

In [ ]:
df_test.drop('HomePlanet',axis=1,inplace=True)

In [ ]:
df_test.drop('Destination',axis=1,inplace=True)

In [ ]:
df_test.drop('VIP',axis=1,inplace=True)

In [ ]:
df_test.fillna(value=True, axis=1, inplace=True)

In [ ]:
df_test['RoomService'].fillna(df_test['RoomService'].mean(),inplace=True)

In [ ]:
df_test['FoodCourt'].fillna(df_test['FoodCourt'].mean(),inplace=True)

In [ ]:
df_test['ShoppingMall'].fillna(df_test['ShoppingMall'].mean(),inplace=True)

In [ ]:
df_test['Spa'].fillna(df_test['Spa'].mean(),inplace=True)

In [ ]:
df_test['VRDeck'].fillna(df_test['VRDeck'].mean(),inplace=True)

# Random Forest
I choose the random forest because it's seems that the categorical variable influences more than numerical. Let's do all the precedure: 

1- Apply LabelEncorder in the categoricals 

In [ ]:
df_train.head(5)

CryoSleep  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Transported
0     False          0.0        0.0           0.0     0.0     0.0        False
1     False        109.0        9.0          25.0   549.0    44.0         True
2     False         43.0     3576.0           0.0  6715.0    49.0        False
3     False          0.0     1283.0         371.0  3329.0   193.0        False
4     False        303.0       70.0         151.0   565.0     2.0         True

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder_CryoSleep = LabelEncoder()
label_econder_transported = LabelEncoder()

In [ ]:
x=df_train.iloc[:,0:6].values
y=df_train.iloc[:,6].values

In [ ]:
x[:,0] = label_encoder_CryoSleep.fit_transform(x[:,0])
y=label_econder_transported.fit_transform(y)

In [ ]:
df=df_test
x_test = df.iloc[:,0:6].values

In [ ]:
# Scaling the data 
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()
x = scaler_census.fit_transform(x)

In [ ]:
scaler_test= StandardScaler()
x_test = scaler_test.fit_transform(x_test)

In [ ]:
import pickle
with open('titanic.pkl',mode='wb') as f:
  pickle.dump([x, y,x_test], f)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
random_forest.fit(x,y)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
previsoes = random_forest.predict(x_test)
previsoes

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
previsoes_back = label_econder_transported.inverse_transform(previsoes)
previsoes_back

array([False, False, False, ..., False,  True, False])

In [ ]:
sub = df_test

In [ ]:
sub

CryoSleep RoomService FoodCourt ShoppingMall     Spa VRDeck
0          True         0.0       0.0          0.0     0.0    0.0
1         False         0.0       9.0          0.0  2823.0    0.0
2          True         0.0       0.0          0.0     0.0    0.0
3         False         0.0    6652.0          0.0   181.0  585.0
4         False        10.0       0.0        635.0     0.0    0.0
...         ...         ...       ...          ...     ...    ...
4272       True         0.0       0.0          0.0     0.0    0.0
4273      False         0.0     847.0         17.0    10.0  144.0
4274       True         0.0       0.0          0.0     0.0    0.0
4275      False         0.0    2680.0          0.0     0.0  523.0
4276       True         0.0       0.0          0.0     0.0    0.0

[4277 rows x 6 columns]

In [ ]:
sub.drop(['CryoSleep','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck',],axis=1,inplace=True)

In [ ]:
sub['Transported'] = pd.DataFrame(previsoes_back)

In [ ]:
sub

Transported
0           False
1           False
2           False
3            True
4            True
...           ...
4272        False
4273        False
4274        False
4275         True
4276        False

[4277 rows x 1 columns]

In [ ]:
sub.to_csv('submission2.csv', index=False)

### SVM

In [ ]:
with open('titanic.pkl','rb') as f:
  X,y,X_test = pickle.load(f)

In [ ]:
from sklearn.svm import SVC
svm_titanic = SVC(kernel='rbf',random_state=0,C=2.0)
svm_titanic.fit(x,y)

SVC(C=2.0, random_state=0)

In [ ]:
previsoes = svm_titanic.predict(x_test)
previsoes

array([1, 0, 1, ..., 1, 1, 1])

In [ ]:
previsoes_back = label_econder_transported.inverse_transform(previsoes)
previsoes_back

array([ True, False,  True, ...,  True,  True,  True])

In [ ]:
sub['PassengerId'] = df_test['PassengerId']

In [ ]:
sub['Transported'] = pd.DataFrame(previsoes_back)

In [ ]:
ne_co = ['PassengerId','Transported']
sub=sub[ne_co] 
sub

PassengerId  Transported
0        0013_01         True
1        0018_01        False
2        0019_01         True
3        0021_01         True
4        0023_01         True
...          ...          ...
4272     9266_02         True
4273     9269_01         True
4274     9271_01         True
4275     9273_01         True
4276     9277_01         True

[4277 rows x 2 columns]

In [ ]:
sub.to_csv('submission3.csv', index=False)

## Neural networks

In [ ]:
import pickle 
with open('titanic.pkl','rb') as f:
  X,y,X_test = pickle.load(f)

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
rede_neural = MLPClassifier(max_iter=1000,hidden_layer_sizes=(200,200),verbose=True,tol=0.0000001,activation='relu')
rede_neural.fit(X,y)

Iteration 1, loss = 0.52656430
Iteration 2, loss = 0.47547794
Iteration 3, loss = 0.46985554
Iteration 4, loss = 0.46934987
Iteration 5, loss = 0.46810191
Iteration 6, loss = 0.46480589
Iteration 7, loss = 0.46420797
Iteration 8, loss = 0.46481125
Iteration 9, loss = 0.46268074
Iteration 10, loss = 0.46026835
Iteration 11, loss = 0.46150168
Iteration 12, loss = 0.46040998
Iteration 13, loss = 0.46124434
Iteration 14, loss = 0.46068813
Iteration 15, loss = 0.45906670
Iteration 16, loss = 0.45907233
Iteration 17, loss = 0.45878945
Iteration 18, loss = 0.45822257
Iteration 19, loss = 0.45890722
Iteration 20, loss = 0.45864206
Iteration 21, loss = 0.45914435
Iteration 22, loss = 0.45729115
Iteration 23, loss = 0.45780905
Iteration 24, loss = 0.45746895
Iteration 25, loss = 0.45586238
Iteration 26, loss = 0.45694103
Iteration 27, loss = 0.45708267
Iteration 28, loss = 0.45732664
Iteration 29, loss = 0.45658766
Iteration 30, loss = 0.45553751
Iteration 31, loss = 0.45582131
Iteration 32, los

MLPClassifier(hidden_layer_sizes=(200, 200), max_iter=1000, tol=1e-07,
              verbose=True)

In [ ]:
previsoes = rede_neural.predict(X_test)
previsoes

array([1, 0, 1, ..., 1, 1, 1])

In [ ]:
previsoes_back = label_econder_transported.inverse_transform(previsoes)
previsoes_back

array([ True, False,  True, ...,  True,  True,  True])

In [ ]:
sub['Transported'] = previsoes_back

PassengerId  Transported
0        0013_01         True
1        0018_01        False
2        0019_01         True
3        0021_01         True
4        0023_01         True
...          ...          ...
4272     9266_02         True
4273     9269_01        False
4274     9271_01         True
4275     9273_01         True
4276     9277_01         True

[4277 rows x 2 columns]

In [ ]:
sub.to_csv('submission4.csv', index=False)